### ISSUE TITLE
does QtPy also pulls the required Qt4/Qt5 dependencies

### ISSUE THREAD

**Issue by houstonian** [janpipek/pydiq#13]
pip install pydiq
Requirement already satisfied: pydiq in ./lib/python3.6/site-packages/pydiq-0.2.1-py3.6.egg
Requirement already satisfied: qtpy in ./lib/python3.6/site-packages/QtPy-1.2.1-py3.6.egg (from pydiq)
Requirement already satisfied: dicom in ./lib/python3.6/site-packages/dicom-0.9.9.post1-py3.6.egg (from pydiq)

I initially had the following error:
qtpy.PythonQtError: No Qt bindings could be found

Had to manually install PyQt4/PyQt5 

Maybe I was doing something wrong?

**Comment by janpipek** [comment]
No, you did not do anything wrong :-) QtPy is working as a wrapper to any version of PyQt/PySide and therefore does not install them. I will update the README...
